name: Detroit Madman
favicon: null
layout_spectrum: 0.40843003359623253
typography_spectrum: 0.60119
title: Comic Kulture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15120d'
    - '#dec487'
    - '#fe0046'
    - '#137efe'
    - '#01e1fd'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
