name: Detroit Madman
favicon: null
layout_spectrum: 0.40843003359623253
typography_spectrum: 0.27096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000116'
    - '#fb352a'
    - '#727272'
    - '#037dd2'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
